version: '3.8'

services:
  proxy-api:
    build: .
    container_name: proxy_airpower_api
    ports:
      - "8081:8080"
    environment:
      # ATENÇÃO: Se o PostgreSQL estiver a correr diretamente na máquina física (Host),
      # use host.docker.internal ou o IP da rede local em vez de 'localhost'.
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.5.0.68:5432/airpower
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234567890
    restart: always