server.port=8080

# Conexão com o PostgreSQL (Lê as variáveis de ambiente ou usa o localhost como padrão para testes)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/nome_do_seu_banco}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234567890}

# Dialeto específico para otimizar queries no Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ddl-auto=update garante que ele NÃO apaga os seus dados antigos, só cria tabelas/colunas novas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false