spring.application.name=Proxy_AirPower
server.port=8080

# 🚨 SEM FALLBACKS! O app só sobe se as variáveis do sistema estiverem configuradas no servidor/Docker
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# 🔐 Credenciais do Super Admin do Painel Web (Lidas do sistema)
airpower.admin.username=${ADMIN_PANEL_USER}
airpower.admin.password=${ADMIN_PANEL_PASS}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false