spring.application.name=Proxy_AirPower
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://10.5.0.68:5434/airpower}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false